# removed the -c option because we need to link this
HelloWorld:
	gcc -shared -Wall -Werror -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux -o libtest.dll.so -fPIC Exploit.c
clean:
	rm -f *.o 
